version: '3'

services:
  server:
    container_name: ecommerce_server
    build: ./server
    restart: always
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
      MONGO_URI: ${MONGO_URI}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    networks: 
      - ecommerce-app
    volumes:
      - ./server/src:/app/src
    command: npm start
    depends_on:
      - mongo
  client:
    container_name: ecommerce_client
    build: ./client
    stdin_open: true
    restart: always
    expose:
      - ${REACT_APP_PORT}
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    networks: 
      - ecommerce-app
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    links:
      - server
    command: npm run start
    depends_on:
      - server
  mongo:
    container_name: ecommerce_mongo
    image: mongo
    environment: 
      - MONGO_INITDB_DATABASE=ecommerce
      # - MONGO_INITDB_ROOT_USERNAME=mongo_user
      # - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - '27017:27017'
    networks: 
      - ecommerce-app
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-data:/data/db
networks: 
  ecommerce-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local